url: http://beta.skelril.com

paginate: 5
paginate_path: "/news/page/:num/"

collections:
  owners:
    output: true
    permalink: /team/:path/
  moderators:
    output: true
    permalink: /team/:path/
  projects:
    output: true
    permalink: /projects/:path/
