url: http://beta.skelril.com
disqus_shortname: skelril

slogan: Minecraft, like never before!
slogan-subtext: Skelril is shaking up Minecraft with innovative mechanics, gameplay, and content found no where else.

paginate: 5
paginate_path: "/news/page/:num/"

collections:
  owners:
    output: true
    permalink: /team/:path/
  moderators:
    output: true
    permalink: /team/:path/
  projects:
    output: true
    permalink: /projects/:path/

feed:
  path: atom.xml

gems:
  - jekyll-feed
